from fastapi import APIRouter
from app.api.v1 import commercial_pricing, commission_payments, commission_rules, disputes as disputes_module, sgp as sgp_module, suppliers, customers, service_points, contracts, commissions, uploads, reconciliation, dashboard, crm, leads, tasks, calllist, proposals, ai_agent, sms as sms_module, email as email_module, landing, renewals, agent_commissions, agent_portal, enrollments, customer_portal, search as search_module, giadienre, saigonllc
from app.api.v1 import auth as auth_module, users as users_module

router = APIRouter(prefix="/api/v1")

router.include_router(auth_module.router, prefix="/auth", tags=["Auth"])
router.include_router(users_module.router, prefix="/users", tags=["Users"])
router.include_router(suppliers.router, prefix="/suppliers", tags=["Suppliers"])
router.include_router(customers.router, prefix="/customers", tags=["Customers"])
router.include_router(service_points.router, prefix="/service-points", tags=["Service Points"])
router.include_router(contracts.router, prefix="/contracts", tags=["Contracts"])
router.include_router(commissions.router, prefix="/commissions", tags=["Commissions"])
router.include_router(uploads.router, prefix="/uploads", tags=["Uploads"])
router.include_router(reconciliation.router, prefix="/reconciliation", tags=["Reconciliation"])
router.include_router(commission_payments.router, prefix="/commission-payments", tags=["Commission Payments"])
router.include_router(commission_rules.router, prefix="/commission-rules", tags=["Commission Rules"])
router.include_router(disputes_module.router, prefix="/disputes", tags=["Disputes"])
router.include_router(sgp_module.router, prefix="/sgp", tags=["SGP Tiers"])
router.include_router(commercial_pricing.router, prefix="/commercial-pricing", tags=["Commercial Pricing"])
router.include_router(dashboard.router, prefix="/dashboard", tags=["Dashboard"])
router.include_router(crm.router, prefix="/crm", tags=["CRM"])
router.include_router(leads.router, prefix="/leads", tags=["Leads"])
router.include_router(tasks.router, prefix="/tasks", tags=["Tasks"])
router.include_router(calllist.router, prefix="/call-list", tags=["Call List"])
router.include_router(proposals.router, prefix="/proposals", tags=["Proposals"])
router.include_router(ai_agent.router, prefix="/ai-agent", tags=["AI Agent"])
router.include_router(sms_module.router, prefix="/sms", tags=["SMS"])
router.include_router(email_module.router, prefix="/email", tags=["Email"])
router.include_router(landing.router, prefix="/landing-plans", tags=["Landing"])
router.include_router(renewals.router, prefix="/renewals", tags=["Renewals"])
router.include_router(agent_commissions.router, prefix="/agent-commissions", tags=["Agent Commissions"])
router.include_router(agent_portal.router, prefix="/agent-portal", tags=["Agent Portal"])
router.include_router(enrollments.router, prefix="/enrollments", tags=["Enrollments"])
router.include_router(customer_portal.router, prefix="/portal", tags=["Customer Portal"])
router.include_router(search_module.router, prefix="/search", tags=["Search"])
# NOTE (multi-session): giadienre powers the live giadienre.com website intake,
# customer portal billing, and CRM module. Do NOT remove when syncing this file.
router.include_router(giadienre.router, prefix="/giadienre", tags=["GiaDienRe"])
# saigonllc.com platform webhooks (power-enrollment CRM sync)
router.include_router(saigonllc.router, prefix="/saigonllc", tags=["SaigonLLC"])
